services:
  router1:
    # É a imagem que será build do router
    build:
      context: ./router
      dockerfile: Dockerfile
    networks:
      sn_6:
        ipv4_address: 172.20.6.2 # É o router anterior
      sn_2:
        ipv4_address: 172.20.2.4 # É o router posterior
      sn_1:
        ipv4_address: 172.20.1.3 # É o router atual
    # 'cap_add' é usado para adicionar capacidades do Linux ao container.
    # Isso permite que o container realize operações privilegiadas específicas
    # que não são concedidas por padrão. Use esta opção com cuidado, pois
    # pode aumentar os riscos de segurança se mal utilizada.
    cap_add:
    - NET_ADMIN
  router2:
    build:
      context: ./router
      dockerfile: Dockerfile
    networks:
      sn_1:
        ipv4_address: 172.20.1.2
      sn_3:
        ipv4_address: 172.20.3.4
      sn_2:
        ipv4_address: 172.20.2.3
    cap_add:
    - NET_ADMIN
  router3:
    build:
      context: ./router
      dockerfile: Dockerfile
    networks:
      sn_2:
        ipv4_address: 172.20.2.2
      sn_4:
        ipv4_address: 172.20.4.4
      sn_3:
        ipv4_address: 172.20.3.3
    cap_add:
    - NET_ADMIN
  router4:
    build:
      context: ./router
      dockerfile: Dockerfile
    networks:
      sn_3:
        ipv4_address: 172.20.3.2
      sn_5:
        ipv4_address: 172.20.5.4
      sn_4:
        ipv4_address: 172.20.4.3
    cap_add:
    - NET_ADMIN
  router5:
    build:
      context: ./router
      dockerfile: Dockerfile
    networks:
      sn_4:
        ipv4_address: 172.20.4.2
      sn_6:
        ipv4_address: 172.20.6.4
      sn_5:
        ipv4_address: 172.20.5.3
    cap_add:
    - NET_ADMIN
  router6:
    build:
      context: ./router
      dockerfile: Dockerfile
    networks:
      sn_5:
        ipv4_address: 172.20.5.2
      sn_1:
        ipv4_address: 172.20.1.4
      sn_6:
        ipv4_address: 172.20.6.3
    cap_add:
    - NET_ADMIN
networks:
  sn_1:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.1.0/24
        gateway: 172.20.1.1
  sn_2:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.2.0/24
        gateway: 172.20.2.1
  sn_3:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.3.0/24
        gateway: 172.20.3.1
  sn_4:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.4.0/24
        gateway: 172.20.4.1
  sn_5:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.5.0/24
        gateway: 172.20.5.1
  sn_6:
    driver: bridge
    ipam:
      config:
      - subnet: 172.20.6.0/24
        gateway: 172.20.6.1