version: '3.8'

services:
  router:
    build:
      context: .
      dockerfile: docker/Dockerfile.router
    networks:
      - network
    ports:
      - "5000:5000"
  
  host:
    build:
      context: .
      dockerfile: docker/Dockerfile.host
    networks:
      - network
    ports:
      - "5001:5001"

networks:
  network:
    driver: bridge